import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers as StoreProvider } from './../store/provider';
import { Toaster } from "@/components/ui/toaster";
import NextTopLoader from "nextjs-toploader";
import { auth } from "@/auth";
import Providers from "@/components/layout/providers";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <div className={'overflow-hidden'}>
            <NextTopLoader showSpinner={false} />
            <Providers session={session}>
              <Toaster />
              {children}
            </Providers>
          </div>

        </StoreProvider>
        <Toaster />
      </body>
    </html>
  );
}
